// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGRSMQbvctoCpaWTuS_Z4_Hx0pNGvpq1I',
    appId: '1:143037380807:web:371d1469109714456226e2',
    messagingSenderId: '143037380807',
    projectId: 'gdghackathon-d3485',
    authDomain: 'gdghackathon-d3485.firebaseapp.com',
    storageBucket: 'gdghackathon-d3485.firebasestorage.app',
    measurementId: 'G-HEWVQN4KWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsvLWUauHb0MhTWttyjOurg63cpdrbdfU',
    appId: '1:143037380807:android:d622731e54c35ece6226e2',
    messagingSenderId: '143037380807',
    projectId: 'gdghackathon-d3485',
    storageBucket: 'gdghackathon-d3485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf_4t4oYF64TxRNneAJVymGVwF35P7TRw',
    appId: '1:143037380807:ios:245659949483ab536226e2',
    messagingSenderId: '143037380807',
    projectId: 'gdghackathon-d3485',
    storageBucket: 'gdghackathon-d3485.firebasestorage.app',
    iosBundleId: 'com.example.gdgHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf_4t4oYF64TxRNneAJVymGVwF35P7TRw',
    appId: '1:143037380807:ios:245659949483ab536226e2',
    messagingSenderId: '143037380807',
    projectId: 'gdghackathon-d3485',
    storageBucket: 'gdghackathon-d3485.firebasestorage.app',
    iosBundleId: 'com.example.gdgHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGRSMQbvctoCpaWTuS_Z4_Hx0pNGvpq1I',
    appId: '1:143037380807:web:afc19b053c9adad46226e2',
    messagingSenderId: '143037380807',
    projectId: 'gdghackathon-d3485',
    authDomain: 'gdghackathon-d3485.firebaseapp.com',
    storageBucket: 'gdghackathon-d3485.firebasestorage.app',
    measurementId: 'G-4Y071V25YK',
  );
}
